### PR TITLE
Add GitHub action for CI

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
See [example runs for this action](https://github.com/stweil/ocrd_froc/actions/workflows/ci.yml).

**Comment by stweil** [comment]
@kba, you can use this action to test your fix for issue #10.

I restricted the test matrix currently to a single test scenario (Ubuntu 22.04, Python 3.9) because running all of them would waste resources, but that can be changed as soon as the issue was fixed.

**Comment by stweil** [comment]
It looks like I should run `ocrd-froc-recognize --help` to get a result code of 0 if there is no crash instead of running `ocrd-froc-recognize` without any argument which always returns 1, even with Python 3.7 and Python 3.8 where it does not crash.

Most OCR-D processors return 1 when they are called without any argument, but `ocrd` from core is an exception which returns 0. Should that be changed?

**Comment by kba** [comment]
Thanks! Will merge once I've fixed the 3.9 issue.

> Most OCR-D processors return 1 when they are called without any argument, but ocrd from core is an exception which returns 0. Should that be changed?

You mean that `ocrd` should return `1` or that `ocrd-*` should return `0`? I don't care either way, but it's easier to just return `0` consistently.

**Pull request merged**
